spring:
  application:
    name: service-provider
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        percentage: 1.0

  # default disable all
  cloud:
    nacos:
      discovery:
        enabled: false
        register-enabled: false
    zookeeper:
      enabled: false
    consul:
      enabled: false


eureka:
  client:
    enabled: false

management:
  health:
    elasticsearch:
      enabled: false

